version: '2'

services:
  app:
    image: 'aliocasha/spring-api:v2'
    build:
      context: .
    container_name: 'spring-api'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ahmadirkistan
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports: 
      - 8080:8080
          
  db:
    image: 'aliocasha/db:v1'
    container_name: 'db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ahmadirkistan