###
POST http://localhost:8080/api/v1/student
Content-Type: application/json

{
    "name": "Nuradin",
    "email": "nuradinnnaiem@gmail.com",
    "dob": "2001-08-02",
    "grade": 12
}
// Add Nuradin Student

###
POST http://localhost:8080/api/v1/student
Content-Type: application/json

{
    "name": "Nuradin",
    "email": "nuradinnnaiem@gmail.com",
    "dob": "2001-08-02",
    "grade": 12
}
// Error : Email Taken

###
POST http://localhost:8080/api/v1/student
Content-Type: application/json

{
    "name": "ramadan",
    "email": "ramadanaiem@gmail.com",
    "dob": "2006-10-11",
    "grade": 9
}
// Add incorrect Ramadan Student

###
GET http://localhost:8080/api/v1/student/9
// Get all students in grade 9

###
GET http://localhost:8080/api/v1/student/16
// Get all students in grade 16

###
GET http://localhost:8080/api/v1/student/133
// Get all students in grade 133

###
DELETE http://localhost:8080/api/v1/student?grade=9
// Delete Students in Grade 9

###
DELETE http://localhost:8080/api/v1/student?grade=312
// Error : No such grade

###
DELETE http://localhost:8080/api/v1/student?id=2
// Delete Student with ID 2

###
DELETE http://localhost:8080/api/v1/student?id=300
// Error : no such id

###
PUT http://localhost:8080/api/v1/student/5?name=Ramadan&email=ramadannaiem@gmail.com
// Correct Ramadan Student with Update

###
PUT http://localhost:8080/api/v1/student/9?name=Ramadan
// Error ID not given
