# DataBase Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-deployment
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
        tier: database
    spec:
      containers:
      - name: postgres
        image: aliocasha/postgres:v1
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-persistance-storage
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-config
                key: DB_NAME
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
        - name: postgres-persistance-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
#Internal Service

apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
    tier: database
spec:
  selector:
    app: db-deployment
    tier: database
  ports:
    - port: 5432
---
#Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi